export enum ROLES {
  MANAGER = "manager",
  STORE_KEEPER = "store_keeper",
}

export const ROLE_LABELS = {
  [ROLES.MANAGER]: "Manager",
  [ROLES.STORE_KEEPER]: "Store Keeper",
} as const;

export enum PERMISSIONS {
  HOME = "/",
  DASHBOARD = "dashboard",
  PRODUCT_VIEW = "product_view",
  PRODUCT_ADD = "product_add",
  PRODUCT_EDIT = "product_edit",
  ANALYTIC = "analytic",
  TRAFFIC = "traffic",
  EARNING = "earning",
  PAYMENT = "payment",
  PAYOUT = "payout",
  ACCOUNT_SETTING = "account_setting",
  MY_PROFILE = "my_profile",
  SECURITY = "security",
  HELP_AND_SUPPORT = "help_and_support",
  FINANCES = "finances",
}

export const ROLE_PERMISSIONS = {
  [ROLES.MANAGER]: [
    PERMISSIONS.HOME,
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.PRODUCT_ADD,
    PERMISSIONS.PRODUCT_EDIT,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.ANALYTIC,
    PERMISSIONS.TRAFFIC,
    PERMISSIONS.EARNING,
    PERMISSIONS.PAYMENT,
    PERMISSIONS.PAYOUT,
    PERMISSIONS.ACCOUNT_SETTING,
    PERMISSIONS.MY_PROFILE,
    PERMISSIONS.SECURITY,
    PERMISSIONS.HELP_AND_SUPPORT,
    PERMISSIONS.FINANCES,
  ],
  [ROLES.STORE_KEEPER]: [
    PERMISSIONS.HOME,
    PERMISSIONS.PRODUCT_ADD,
    PERMISSIONS.PRODUCT_EDIT,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.ANALYTIC,
    PERMISSIONS.TRAFFIC,
    PERMISSIONS.EARNING,
    PERMISSIONS.PAYMENT,
    PERMISSIONS.PAYOUT,
    PERMISSIONS.ACCOUNT_SETTING,
    PERMISSIONS.MY_PROFILE,
    PERMISSIONS.SECURITY,
    PERMISSIONS.HELP_AND_SUPPORT,
    PERMISSIONS.FINANCES,
  ],
};

export function hasPermission(role: ROLES, permission: PERMISSIONS) {
  return ROLE_PERMISSIONS[role]?.includes(permission);
}
